// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Srv.Data;

#nullable disable

namespace Srv.Migrations
{
    [DbContext(typeof(MiniCourseDbContext))]
    [Migration("20230324140403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Middle.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is 1th post and 1th example",
                            Title = "1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is 2th post and 2th example",
                            Title = "2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is 3th post and 3th example",
                            Title = "3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is 4th post and 4th example",
                            Title = "4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is 5th post and 5th example",
                            Title = "5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is 6th post and 6th example",
                            Title = "6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
